apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::798118821103:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BMPM6FCKWNFY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::798118821103:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-20T14:39:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-20T14:39:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1340"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b3468459-3b5f-4aa8-b550-f9e36527a05c
